title: Jun Poh # your name (or website title) here
logo: "/images/head_shot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with 4 years of commercial experience in analytics, strategy and product market research. 
  <br><br>
  Previously at McDonaldâ€™s, specializes in turning complex problems into clear solutions through strategy and storytelling. Driven by curiosity, data, and the pursuit of impact. 
  <br><br>
  Msc Data Science (Distinction), University of Sydney
  <br><br>
  BS Electrical and Electronics Engineering, RMIT University
  <br><br>
  <a href="https://www.linkedin.com/in/junpoh/">View my LinkedIn Profile</a> 
  

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'

